package wizardry.compendium.wire

import kotlinx.serialization.json.JsonObject

/**
 * Migrates an envelope JSON object from one wire format version to the next.
 *
 * # Generated vs hand-written
 *
 * Most migrators are auto-generated by the wire-ksp processor in response to
 * mechanical schema changes (field renames, additive enum changes). When a
 * change is non-mechanical (type splits, enum reorders, semantic conversions),
 * the processor emits a stub that fails the build until a developer fills in
 * the body.
 *
 * # Idempotence is NOT required
 *
 * The migrator chain runs each version step exactly once. Implementations may
 * assume input is in the `from` shape and may produce output strictly in the
 * `to` shape; they need not be safe to run twice.
 *
 * # Why JsonObject and not the typed model
 *
 * Migrators operate on the raw `JsonObject` rather than a deserialized type
 * because the typed wire classes only describe the *current* version. We
 * deliberately do not keep frozen copies of every prior version's data
 * classes around — that lock-in is what migrations exist to avoid. Working
 * on the JsonObject keeps each migrator's input/output coupling local to its
 * `from` and `to` versions.
 */
interface WireMigrator {
    /** Source version this migrator reads. */
    val from: Int

    /** Destination version this migrator produces. */
    val to: Int

    /**
     * Convert an envelope from `from` shape to `to` shape. Implementations
     * should return a *new* JsonObject rather than mutating the input.
     */
    fun migrate(envelope: JsonObject): JsonObject
}

/**
 * Helper for generated migrators: rename a field on a JsonObject. Returns a
 * new object with `oldKey` removed and its value associated with `newKey`.
 * No-op when `oldKey` is not present.
 */
fun JsonObject.renameField(oldKey: String, newKey: String): JsonObject {
    if (oldKey !in this) return this
    val mutable = toMutableMap()
    val value = mutable.remove(oldKey) ?: return this
    mutable[newKey] = value
    return JsonObject(mutable)
}
