package wizardry.compendium.wire.ksp

/**
 * Generates Kotlin source for `WireMigrator` implementations from a list of
 * schema changes that the diff engine classifies as `AutoMigrator` or
 * `NeedsManualMigrator`.
 *
 * # Output shape
 *
 * For a v(N-1) → v(N) bump, this produces a single file:
 *
 *     wizardry.compendium.wire.generated.MigratorVNm1ToVN
 *
 * containing one `WireMigrator` object that applies all auto-migrate-able
 * changes. If any non-mechanical changes are present, the file additionally
 * contains a `// TODO` block detailing each non-mechanical change with
 * concrete instructions, and the body throws `NotImplementedError` to fail
 * loudly at import time. The KSP processor *also* reports a build error so
 * the developer doesn't ship a half-finished migrator.
 *
 * # Why `object` and not `class`
 *
 * Migrators are stateless. An object literal is cheaper at runtime, easier
 * to register, and doesn't pollute the type hierarchy. If a future migrator
 * ever needs configuration, switch to `class` then; until then keep it terse.
 *
 * # Why we generate one big migrator per version step
 *
 * Each schema-bump produces one chain link. The runtime registry composes
 * them in order. One file per step keeps the bookkeeping simple — the
 * processor doesn't need to coordinate multiple files for the same version
 * jump. Could split per-change later if a migrator gets too large to read.
 *
 * # Limitations
 *
 * - **Only top-level renames.** As described in `SchemaDiff.kt`, nested-type
 *   renames are tagged `NeedsManualMigrator`. The generated stub points the
 *   developer at the body to fill in.
 * - **No transformation of values.** We only rename keys; we never coerce
 *   their values. Any time a wire format change implies a value transform
 *   (`Int` to `String`, splitting one field into two), the dev writes that
 *   migrator by hand.
 */
internal object MigratorGenerator {

    fun generate(
        fromVersion: Int,
        toVersion: Int,
        changes: List<SchemaChange>,
    ): String {
        val needsManualBlocks = changes.filter { it.classification == SchemaChange.Classification.NeedsManualMigrator }
        val autoChanges = changes.filter { it.classification == SchemaChange.Classification.AutoMigrator }
        val mechChanges = changes.filter { it.classification == SchemaChange.Classification.Mechanical }
        val className = "MigratorV${fromVersion}ToV${toVersion}"

        val builder = StringBuilder()
        builder.appendLine("// AUTO-GENERATED — DO NOT EDIT")
        builder.appendLine("// Generated by wire-ksp from the v$fromVersion → v$toVersion schema diff.")
        builder.appendLine("// Mechanical (no migration needed): ${mechChanges.size}")
        builder.appendLine("// Auto-migrated: ${autoChanges.size}")
        builder.appendLine("// Needs manual migration: ${needsManualBlocks.size}")
        builder.appendLine("package wizardry.compendium.wire.generated")
        builder.appendLine()
        builder.appendLine("import kotlinx.serialization.json.JsonObject")
        builder.appendLine("import wizardry.compendium.wire.WireMigrator")
        // Only import the rename helper when we actually call it. Avoids
        // generating unused-import warnings in the consumer's compile log
        // and keeps the generated file scoped to what it needs.
        val emitsRenames = autoChanges.any { it is SchemaChange.FieldRenamed && it.onEnvelope }
        if (emitsRenames) {
            builder.appendLine("import wizardry.compendium.wire.renameField")
        }
        builder.appendLine()

        // Document each detected change in the comment block. This is the
        // first thing a reviewer will look at after a version bump, so it
        // pays to be very explicit here.
        builder.appendLine("/**")
        builder.appendLine(" * Schema changes detected:")
        for (c in changes) {
            builder.append(" *  - ")
            builder.append(c.classification.name)
            builder.append(": ")
            builder.appendLine(c.describe())
        }
        builder.appendLine(" */")

        builder.appendLine("object $className : WireMigrator {")
        builder.appendLine("    override val from: Int = $fromVersion")
        builder.appendLine("    override val to: Int = $toVersion")
        builder.appendLine()
        builder.appendLine("    override fun migrate(envelope: JsonObject): JsonObject {")

        if (needsManualBlocks.isNotEmpty()) {
            // The processor will also fail the build, but if generation
            // somehow proceeds (e.g., dev silenced the error), the runtime
            // throws as well. Belt and suspenders.
            builder.appendLine("        // TODO(${className}): the schema diff includes non-mechanical changes.")
            builder.appendLine("        // Fill in the migration logic for these and remove the throw below.")
            for (c in needsManualBlocks) {
                builder.append("        //   - ")
                builder.appendLine(c.describe())
            }
            builder.appendLine("        throw NotImplementedError(")
            builder.appendLine("            \"Migrator $className is incomplete. \" +")
            builder.appendLine("            \"See TODO comments in the generated file for required changes.\"")
            builder.appendLine("        )")
        } else {
            builder.appendLine("        var current = envelope")
            // Auto: top-level field renames (envelope-scoped).
            for (c in autoChanges) {
                if (c is SchemaChange.FieldRenamed && c.onEnvelope) {
                    builder.append("        current = current.renameField(\"")
                    builder.append(c.oldAlias)
                    builder.append("\", \"")
                    builder.append(c.newAlias)
                    builder.appendLine("\")")
                }
            }
            // Mechanical changes are all no-ops at migration time. Document them
            // for the reader's benefit but emit nothing.
            builder.appendLine("        return current")
        }

        builder.appendLine("    }")
        builder.appendLine("}")

        return builder.toString()
    }

    private fun SchemaChange.describe(): String = when (this) {
        is SchemaChange.TypeAdded -> "type added: $fqn"
        is SchemaChange.TypeRemoved -> "type removed: $fqn"
        is SchemaChange.FieldAdded -> "field added on $typeFqn: $fieldName (alias=$alias, hasDefault=$hasDefault)"
        is SchemaChange.FieldRemoved -> "field removed on $typeFqn: $fieldName (alias=$alias)"
        is SchemaChange.FieldRenamed -> "field renamed on $typeFqn.$fieldName: $oldAlias → $newAlias (onEnvelope=$onEnvelope)"
        is SchemaChange.FieldTypeChanged -> "field type changed on $typeFqn.$fieldName: $oldType → $newType"
        is SchemaChange.EnumValueAppended -> "enum value appended on $fqn: $value"
        is SchemaChange.EnumReshaped -> "enum reshaped on $fqn: $previousEntries → $currentEntries"
    }
}
