package wizardry.compendium.wire.ksp

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

/**
 * Generates Kotlin source for `WireMigrator` implementations from a list of
 * schema changes.
 *
 * # Output shape
 *
 * For a v(N-1) → v(N) bump, this produces a single file at
 * `wizardry.compendium.wire.generated.MigratorVNm1ToVN` containing one
 * `WireMigrator` object that applies all auto-migrate-able changes. If any
 * non-mechanical changes are present, the generated body throws
 * `NotImplementedError` and the processor reports a build error.
 *
 * # Why KotlinPoet
 *
 * KotlinPoet handles indentation, imports, and edge cases (escaping, kdoc,
 * nullability) for us. The previous string-builder approach was error-prone
 * and produced sub-par output (manual import tracking, hand-formatted code).
 *
 * # Hand-edits to non-mechanical migrators
 *
 * When the diff includes a `NeedsManualMigrator` change, the dev MUST move
 * the generated file from `build/generated/ksp/` to a committed source path
 * (same FQN) and fill in the body. The generated stub is a starting point;
 * any subsequent build will re-emit a fresh stub at the build-generated
 * path, but the runtime classloader resolves the committed one first if
 * the same FQN exists in source. Important: only one of (committed,
 * auto-generated) can exist for a given version pair, otherwise the build
 * fails with a duplicate-class error from kotlinc. Convention: the dev
 * deletes the auto-generated file from build/ once they commit a manual
 * version. Future tier improvement: have the processor detect a committed
 * `MigratorVxToVy` source and skip auto-generation for that version pair.
 */
internal object MigratorGenerator {

    fun fileSpec(
        fromVersion: Int,
        toVersion: Int,
        changes: List<SchemaChange>,
    ): FileSpec {
        val needsManual = changes.any { it.classification == SchemaChange.Classification.NeedsManualMigrator }
        val auto = changes.filter { it.classification == SchemaChange.Classification.AutoMigrator }
        val mechanical = changes.filter { it.classification == SchemaChange.Classification.Mechanical }
        val className = "MigratorV${fromVersion}ToV${toVersion}"

        val migrateFn = FunSpec.builder("migrate")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("envelope", JSON_OBJECT)
            .returns(JSON_OBJECT)
            .also { fn ->
                if (needsManual) {
                    fn.addCode(buildStubBody(className, changes))
                } else {
                    fn.addCode(buildAutoBody(auto))
                }
            }
            .build()

        val migratorObject = TypeSpec.objectBuilder(className)
            .addKdoc(buildKdoc(fromVersion, toVersion, mechanical, auto, changes.filter { it.classification == SchemaChange.Classification.NeedsManualMigrator }))
            .addSuperinterface(WIRE_MIGRATOR)
            .addProperty(
                PropertySpec.builder("from", INT)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%L", fromVersion)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("to", INT)
                    .addModifiers(KModifier.OVERRIDE)
                    .initializer("%L", toVersion)
                    .build(),
            )
            .addFunction(migrateFn)
            .build()

        return FileSpec.builder(GENERATED_PACKAGE, className)
            .addFileComment("AUTO-GENERATED — DO NOT EDIT\n")
            .addFileComment("Generated by wire-ksp from the v$fromVersion → v$toVersion schema diff.")
            .addType(migratorObject)
            .build()
    }

    private fun buildKdoc(
        fromVersion: Int,
        toVersion: Int,
        mechanical: List<SchemaChange>,
        auto: List<SchemaChange>,
        manual: List<SchemaChange>,
    ): CodeBlock = CodeBlock.builder().apply {
        addStatement("Migrator from wire format v%L to v%L.\n", fromVersion, toVersion)
        addStatement("Schema changes detected:")
        for (c in mechanical) addStatement(" - mechanical: %L", c.describe())
        for (c in auto) addStatement(" - auto-migrated: %L", c.describe())
        for (c in manual) addStatement(" - **needs manual migration**: %L", c.describe())
    }.build()

    private fun buildAutoBody(autoChanges: List<SchemaChange>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.addStatement("var current = envelope")
        for (c in autoChanges) {
            if (c is SchemaChange.FieldRenamed && c.onEnvelope) {
                builder.addStatement(
                    "current = current.%M(%S, %S)",
                    RENAME_FIELD,
                    c.oldAlias,
                    c.newAlias,
                )
            }
        }
        builder.addStatement("return current")
        return builder.build()
    }

    private fun buildStubBody(className: String, changes: List<SchemaChange>): CodeBlock {
        val builder = CodeBlock.builder()
        builder.addStatement("// TODO(%L): the schema diff includes non-mechanical changes.", className)
        builder.addStatement("// Fill in the migration logic for these and remove the throw below.")
        for (c in changes.filter { it.classification == SchemaChange.Classification.NeedsManualMigrator }) {
            builder.addStatement("//   - %L", c.describe())
        }
        // Use a multi-line throw to keep the generated source readable.
        builder.add(
            "throw %T(\n" +
                "    %S +\n" +
                "    %S\n" +
                ")\n",
            ClassName("kotlin", "NotImplementedError"),
            "Migrator $className is incomplete. ",
            "See TODO comments in the generated file for required changes.",
        )
        return builder.build()
    }

    private fun SchemaChange.describe(): String = when (this) {
        is SchemaChange.TypeAdded -> "type added: $fqn"
        is SchemaChange.TypeRemoved -> "type removed: $fqn"
        is SchemaChange.FieldAdded -> "field added on $typeFqn: $fieldName (alias=$alias, hasDefault=$hasDefault)"
        is SchemaChange.FieldRemoved -> "field removed on $typeFqn: $fieldName (alias=$alias)"
        is SchemaChange.FieldRenamed -> "field renamed on $typeFqn.$fieldName: $oldAlias → $newAlias (onEnvelope=$onEnvelope)"
        is SchemaChange.FieldTypeChanged -> "field type changed on $typeFqn.$fieldName: $oldType → $newType"
        is SchemaChange.EnumValueAppended -> "enum value appended on $fqn: $value"
        is SchemaChange.EnumReshaped -> "enum reshaped on $fqn: $previousEntries → $currentEntries"
    }

    private const val GENERATED_PACKAGE = "wizardry.compendium.wire.generated"
    private val JSON_OBJECT = ClassName("kotlinx.serialization.json", "JsonObject")
    private val WIRE_MIGRATOR = ClassName("wizardry.compendium.wire", "WireMigrator")
    private val RENAME_FIELD = MemberName("wizardry.compendium.wire", "renameField")
}
